### ISSUE TITLE
Provenance page has garbled formatting

### ISSUE THREAD

**Issue by MarkLodato** [devmoran/slsa#6]
Looks like the CSS is a bit garbled on the provenance page:

* `ul > li` bullets are not showing up.
* Missing space between paragraphs.

![image](https://user-images.githubusercontent.com/58860/146061532-bc106766-018b-40fc-9df0-42c453235017.png)
![image](https://user-images.githubusercontent.com/58860/146061866-1faabc6d-539f-489d-9e4f-921937310515.png)

**Comment by devmoran** [comment]
Fixed as of d9e0658dd6b3525f0655e2a856a9322a425c8bf3
